### PR TITLE
Out-of-date gems (fixes #619)

### LINKED ISSUE #619: faraday gem out-of-date
Would it be possible to update the gem `faraday` to version `0.9.x`?

Thank you.

### PR DESCRIPTION
**Pull request by lucascaton**

### CODE REVIEW

**Comment by lucascaton** [comment]
Hey @tombruijn!

I keep the `backup` gem in the `Gemfile` in order to not forget to install it when updating the Ruby version in the server, because `rbenv` keeps gems in separate places for different Ruby versions.

The problem is that others gem requires `faraday` `0.9.0` or newer, so right now I'm not able to include `backup` gem to the `Gemfile`.

Thank you.

**Comment by tombruijn** [comment]
@lucascaton in what Gemfile are you adding it? The Gemfile of your Rails application? It's recommended to create a separate project for your backup configuration with its own Gemfile that pretty much only contains `gem "backup"`.

Let me know if my assumption was correct or not.

---

What I usually post when I see people adding backup to their rails project Gemfile:

> I see you have backup in the same Gemfile as your rails project. This is not recommended. Instead we recommend using a separate project to install and configure backup. It not designed to play nice with other installations due to it's rather harsh gem version locks.

**Comment by lucascaton** [comment]
@tombruijn Yes, but as I explained, we usually put it in the project's `Gemfile` (of all of our projects).

I can't see any problem to update the gems.

**Comment by tombruijn** [comment]
@lucascaton as I explained, you shouldn't do that. With the hard version locks this gem has it isn't meant to be included in the same bundle as another gem/framework.

This was done long before I joined the project, but I can see why this was done. Other people might also include this in their (rails) projects (which they shouldn't) or have added other gems to their bundle to setup other (experimental) integrations. If we just update it for the sake of updating (it's a different story for bugs and security issues) other setups might break when they update. So we will get another issue/PR, and another one, etc. And since we've burned ourselves already on "just updating" other gems I'm a little hesitant to merge this.

So unless there's a real bug or security issue I will not merge gem version bumps for compatibility in other projects.

This certainly isn't the best approach, but it's the direction this gem is currently on forced by its design. I promise that future versions won't have this problem, but it's nowhere near release just yet. We're working on it though.

**Comment by lucascaton** [comment]
@tombruijn No problem, thanks anyway ツ

**Pull request closed without merging**
